attributes:
  is_child:
    type: bool
    multiple: false
    index_keys:
      - "is_child_bsi"
    predicate: "http://id.loc.gov/vocabulary/identifiers/isChild"
  split_from_pdf_id:
    type: string
    multiple: false
    index_keys:
      - "split_from_pdf_id_ssi"
    predicate: "http://id.loc.gov/vocabulary/identifiers/splitFromPdfId"
