name: "Build Lint Test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@iiif-v6
    secrets: inherit
    with:
      platforms: "linux/amd64"
      target: hyku-base
      worker: false
      db: false
  test:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@iiif-v6
  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@iiif-v6
